version: '3.4'

services:
  shoppingcartservice:
    image: shoppingcartservice:dev
    container_name: ShoppingCartService
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "ShoppingCartService"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/samgold/Desktop/manning_liveProjects/CSharpDevTesting/VS/SG_P1_FINAL/ShoppingCartService:/app
      - /Users/samgold/Desktop/manning_liveProjects/CSharpDevTesting/VS/SG_P1_FINAL:/src
      - /Users/samgold/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/samgold/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net5.0/ShoppingCartService.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true